# Generated by Django 3.1.7 on 2021-04-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice')),
            ],
        ),
    ]
