# Generated by Django 3.1.7 on 2021-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedevice',
            name='note',
            field=models.TextField(default='Your Service Is Expired.', null=True),
        ),
    ]
