# Generated by Django 3.2 on 2022-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remotedevice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='MAC Address'),
        ),
    ]
