# Generated by Django 3.2 on 2022-09-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('core', '0004_alter_remotedevice_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedevice',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_device', to='fcm_django.fcmdevice'),
        ),
    ]
